### ISSUE TITLE
Error when <CR>ing

### ISSUE THREAD

**Issue by utrack** [Osse/double-tap#5] opened 2015-06-07 10:19 UTC
Errors pop out when I press Enter in Insert mode, referring to DoubleTap.
http://i.imgur.com/OZDTEyu.jpg
Maybe some other binding breaks it, but there's no other inoremaps or imaps for <CR>...

**Comment by Osse** [comment] 2015-06-08 22:36
I thought I fixed this a couple of days ago but I only discovered it...

The problem is that the comment string Double-tap find is valid regex itself, so you end up with `**` which is invalid; at least for C. The filetype in question here is Go, right?

**Comment by utrack** [comment] 2015-06-09 11:12
Yup, it's Go.
I tried to debug it myself, check the PR please. : )

**Comment by JoshMermel** [comment] 2015-09-03 14:20
I am also effected by this bug in languages where * is used as part of comment leaders (C,C++,Go...).

I tested utrack's pull request and found that it worked in Go however it broke the functionality of the plugin in C and C++ for me.  In those language, hitting enter on an empty comment line inserts a <CR> rather than a <C-u>.

**Comment by utrack** [comment] 2015-09-09 12:20
@JoshMermel Yep, I found bugs with SQL queries as well. I'll try to look for alternate approaches and fix everything around next week.

**Comment by Osse** [comment] 2015-09-09 22:41
Hi guys.

As you few users have maybe noticed I've pretty much neglected this plugin... Sorry about that. I even didn't use it myself for a while. 

Anyway, I just committed a fix for this particular issue.

**Closed** 2015-09-09 22:41 UTC

**Comment by Osse** [comment] 2015-09-09 22:59
Heh, Github reveals my push -f habits...

**Comment by JoshMermel** [comment] 2015-09-10 13:47
Woah, thank you!  The plugin no longer crashes for me in C++ but its behavior is not exactly what I want.

/*
* for comment of this style it replaces <CR> with <C-u> 
*/

// but for comments of this style it seems to do nothing

**Comment by Osse** [comment] 2015-09-10 14:53
Yes. It would make sense to change the \* into */ in this case but I'm not sure that's behaviour I personally want from this plugin. But maybe others do?

Handling // should be straight-forward in principle. Currently the problem is that Double-tap can only detect one such comment marker per filetype and in C/C++ (and presumably Go) the \* style is detected first.

**Comment by JoshMermel** [comment] 2015-09-10 20:41
I think it would be cool if the plugin changed the last \* to a */ but I can see arguments both ways.  I use comments of the "//" form far more often than the "/* */" form so I swapped the order of the two in my cpp comments setting by adding the following to my vimrc

```
au filetype cpp setlocal comments=://,s1:/*,mb:*,ex:*/
```
